spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reservation
      auto-create-index: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: konvicted734@gmail.com
    password: ugszsiraljepnomz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
